name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.6 # This is the action
        with:
          heroku_api_key: 74ecae4a-d13d-44da-abe0-bba7e6d9d5a6
          heroku_app_name: tahoo #Must be unique in Heroku
          heroku_email: toni@tahoo.fi
          usedocker: true
