name: Deploy tahoo

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy tahoo files to scp
        uses: appleboy/scp-action@master
        with:
          host: hotelli03.domainhotelli.fi
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: "routes,resources"
          target: "public_html"
        with:
          host: hotelli03.domainhotelli.fi
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: "app/http"
          target: "public_html/app/http"   